version: '3.7'
services:
  auth:
    container_name: auth
    image: auth
    build: .
    depends_on:
      - auth_db
  auth_db:
    container_name: auth-db
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
networks:
  last-message-backend:
    name: last-message-backend
