version: '3.7'
services:
  message:
    networks:
      - last-message-backend
    container_name: message
    image: message
    build: .
    ports:
      - 8081:8081
    depends_on:
      - message_db
  message_db:
    container_name: message-db
    image: postgres
    restart: on-failure
    networks:
      - last-message-backend
    ports:
      - 5001:5432
    environment:
      POSTGRES_DB: messagedb
      POSTGRES_USER: message
      POSTGRES_PASSWORD: message
  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - last-message-backend
    ports:
      - 6379:6379

networks:
  last-message-backend:
    name: last-message-backend
