version: '3.7'
services:
  notification:
    networks:
      - last-message-backend
    container_name: notification
    image: notification
    build: .
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    networks:
      - last-message-backend
networks:
  last-message-backend:
    name: last-message-backend