version: '3.7'
services:
  notification:
    container_name: notification
    image: notification
    build: .
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
networks:
  last-message-backend:
    name: last-message-backend